name: Run new-release script

on: repository_dispatch

jobs:
  generate_diffs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - name: Install Dependencies
        run: yarn
      - name: Run new-release script
        run: ./new-release.sh ${{ github.event.client_payload.version }}
